# Generated by Django 3.1.5 on 2021-01-13 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('published', 'Published'), ('status', 'Status')], default='published', max_length=15),
        ),
    ]
